### ISSUE TITLE
Make templates work to use client branding

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#101]
From scope:

> Contractor will ensure that each template can be modified such that the font and color schemes may align with non-OMNI entities.

**Comment by dgkeyes** [comment]
@OskaratOmni just to confirm, you want to have the ability for the report templates to reflect client branding, right? I know we are going to do this for ggplot, but I want to make sure you also want to do it for the templates.

**Comment by OskaratOmni** [comment]
Hey @dgkeyes , 
Yes, but with branding limited to font and colors. 
Although I bet people will request that we can add a logo for the client in place of ours as well, so we should include that possibility (or at least ability to remove OMNI logo).

**Comment by JosephBARBIERDARNAL** [comment]
Note for me: check pagedreport package

**Comment by JosephBARBIERDARNAL** [comment]
@dgkeyes Currently it only works for pdf report, but applying the same thing to other templates should be relatively simple now. Let me know what you think:

- by default, to use OMNI style, the yaml header should looks like this:

```yaml
output:
  omni::pdf_report
```

- now, it's possible to add the following arguments:

```yaml
output:
  omni::pdf_report:
    main_font: "Times New Roman"
    secondary_font: "Helvetica"
    background_color: "#677384"
    primary_color: "rgb(100, 200, 100)"
    remove_logo: TRUE
```

Note: I only added an option to remove logo (the ones in the bottom of the pages and the one on the cover page), because using other logos is quite tricky.
