### ISSUE TITLE
Add option in YAML to switch cover image

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#129]
![Image](https://github.com/user-attachments/assets/09c9f605-4194-4985-a439-3f7d0485a70f)

We want to do two things here:

- [x] Change the default image to the teal or plum. @OskaratOmni if you could tell us which one you want and post the exact image here or tell us the filename that would be helpful.
- [ ] Add option in YAML to switch cover image.

@JosephBARBIERDARNAL let's get a v1 of the report template and then work on this later.

**Comment by OskaratOmni** [comment]
let's go with Pattern-07-Periwinkle
Thanks!

**Comment by dgkeyes** [comment]
Changed the cover image in 5118bf0eed158c6f99dadb1a8829416c373925ff

![Image](https://github.com/user-attachments/assets/f8ca4425-f378-4617-b18a-9ba79873c8a3)

**Comment by dgkeyes** [comment]
@JosephBARBIERDARNAL we can add an option in the YAML to switch the cover image. @OskaratOmni do you want to give people a few color and/or pattern number options they can choose from? For example, they can only choose perwinkle pattern 7 or teal pattern 6.

**Comment by dgkeyes** [comment]
Thanks @OskaratOmni. We'll work on this a bit later.

**Comment by JosephBARBIERDARNAL** [comment]
@dgkeyes @OskaratOmni I added the following argument in the yaml:

```yaml
output:
  omni::pdf_report:
    main_font: "Inter Tight"
    secondary_font: "Sometype Mono"
    background_color: "#f9f7f4"
    primary_color: "#081c39"
    remove_logo: FALSE
    remove_cover_page: FALSE
    background_cover_image: "01-Yellow" # here
```

It's documented so it will appear on the website, but in short it accepts any value from `c("01-yellow", "02-teal", "03-orangered", "06-teal", "07-periwinkle", "07-olive", "08-plum")` (case insensitive).

It's in this PR: #135
