### ISSUE TITLE
Create Word template

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#23]
From @oskaratomni:

> templates for multiple output formats. It would be nice to readily knit to Word, pdf, or html, with each using OMNI fonts and color schemes.

**Comment by tvroylandt** [comment]
YAML header for the template :

```
title: "Tapi subgroup analysis"
author: "Oskar"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::word_document2:
    reference_docx: word_template.docx
    toc: no
    toc_float: no
    fig_caption: yes
    number_sections: yes
editor_options:
  chunk_output_type: console
always_allow_html: yes

```

And I need to add a \newpage before the text starts. 

TO DO :

- wrap in package
- add columns layout (explore Quarto option ?)
